import * as vscode from 'vscode';
import { AdoConfig } from '../config';
import { getCompletedStories, WorkItem } from '../adoClient';

export async function runReleaseNotes(
  cfg: AdoConfig,
  model: vscode.LanguageModelChat,
  stream: vscode.ChatResponseStream,
  version?: string
): Promise<void> {
  const releaseVersion = version ?? cfg.sprintName;
  stream.markdown(`## 📋 Release Notes — ${releaseVersion}\n\n`);
  stream.markdown(`Fetching completed stories...\n\n`);

  const stories = await getCompletedStories(cfg);
  if (!stories.length) {
    stream.markdown(`> No completed stories found in **${cfg.iterationPath}**. Make sure stories are set to "Done".`);
    return;
  }

  stream.markdown(`Found **${stories.length} completed stories**. Generating release notes...\n\n`);

  const prompt = buildReleaseNotesPrompt(stories, releaseVersion, cfg.sprintName);
  const messages = [vscode.LanguageModelChatMessage.User(prompt)];
  const response = await model.sendRequest(messages, {}, new vscode.CancellationTokenSource().token);

  let notes = '';
  for await (const chunk of response.text) {
    notes += chunk;
    stream.markdown(chunk);
  }

  stream.markdown(`\n\n---\n`);
  stream.markdown(`### Story Summary\n`);
  stream.markdown(`| # | Title | Points |\n|---|-------|--------|\n`);
  for (const s of stories) {
    stream.markdown(`| #${s.id} | ${s.title} | ${s.storyPoints} pts |\n`);
  }

  const totalPoints = stories.reduce((s, x) => s + x.storyPoints, 0);
  stream.markdown(`\n**Total:** ${stories.length} stories · ${totalPoints} story points delivered\n`);
  stream.markdown(`\n_Generated by @ScrumAgent /ReleaseNotes on ${new Date().toDateString()}_`);
}

function buildReleaseNotesPrompt(stories: WorkItem[], version: string, sprint: string): string {
  const storySummaries = stories.map(s =>
    `- #${s.id}: ${s.title}\n  Tags: ${s.tags || 'none'}\n  Description: ${s.description?.substring(0, 150) || 'N/A'}`
  ).join('\n\n');

  return `You are a technical writer generating professional release notes for stakeholders.

Version: ${version}
Sprint: ${sprint}
Release Date: ${new Date().toDateString()}

Completed User Stories:
${storySummaries}

Write release notes with these sections. Group stories under the most appropriate section:

# Release Notes — ${version}

## ✨ New Features
(bullet list — each item references the story number)

## 🐛 Bug Fixes
(bullet list — if no bug fixes, write "None in this release")

## 📈 Improvements
(bullet list)

## ⚠️ Breaking Changes
(bullet list — if none, write "None")

## 📦 What's Included
(short paragraph summarising the release value to end users)

Keep it professional, non-technical where possible, suitable for stakeholders and end users.`;
}
